export default {
  id: 'ab34762f-ccd1-4258-b3e1-69558728e6b4',
  container: {
    height: 1700,
    width: 2100,
    length: 3000,
    unit: 'mm',
    goods: [
      {
        id: 1,
        desc: 'Palette 1',
        height: 1000,
        group: 1,
        width: 1050,
        length: 1000,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 0,
        y: 0,
        z: 0,
        sequenceNr: 0,
      },
      {
        id: 2,
        desc: 'Palette 1',
        height: 1000,
        group: 1,
        width: 1050,
        length: 1000,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 1050,
        y: 0,
        z: 0,
        sequenceNr: 1,
      },
      {
        id: 4,
        desc: 'Palette 1',
        height: 1000,
        group: 1,
        width: 1050,
        length: 1000,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 0,
        y: 0,
        z: 1000,
        sequenceNr: 3,
      },
      {
        id: 5,
        desc: 'Palette 1',
        height: 1000,
        group: 1,
        width: 1050,
        length: 1000,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 1050,
        y: 0,
        z: 1000,
        sequenceNr: 4,
      },
      {
        id: 8,
        desc: 'Palette 1',
        height: 1000,
        group: 1,
        width: 1050,
        length: 1000,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 0,
        y: 0,
        z: 2000,
        sequenceNr: 7,
      },
      {
        id: 9,
        desc: 'Palette 1',
        height: 1000,
        group: 1,
        width: 1050,
        length: 1000,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 1050,
        y: 0,
        z: 2000,
        sequenceNr: 8,
      },
      {
        id: 12,
        desc: 'Palette 2',
        height: 400,
        group: 1,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 0,
        y: 1000,
        z: 0,
        sequenceNr: 11,
      },
      {
        id: 13,
        desc: 'Palette 2',
        height: 400,
        group: 1,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 700,
        y: 1000,
        z: 0,
        sequenceNr: 12,
      },
      {
        id: 15,
        desc: 'Palette 2',
        height: 400,
        group: 1,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 1400,
        y: 1000,
        z: 0,
        sequenceNr: 14,
      },
      {
        id: 17,
        desc: 'Palette 2',
        height: 400,
        group: 1,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 0,
        y: 1000,
        z: 500,
        sequenceNr: 16,
      },
      {
        id: 18,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 700,
        y: 1000,
        z: 500,
        sequenceNr: 17,
      },
      {
        id: 20,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 1400,
        y: 1000,
        z: 500,
        sequenceNr: 19,
      },
      {
        id: 23,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 0,
        y: 1000,
        z: 1000,
        sequenceNr: 22,
      },
      {
        id: 24,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 700,
        y: 1000,
        z: 1000,
        sequenceNr: 23,
      },
      {
        id: 26,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 1400,
        y: 1000,
        z: 1000,
        sequenceNr: 25,
      },
      {
        id: 29,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 0,
        y: 1000,
        z: 1500,
        sequenceNr: 28,
      },
      {
        id: 30,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 700,
        y: 1000,
        z: 1500,
        sequenceNr: 29,
      },
      {
        id: 32,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 1400,
        y: 1000,
        z: 1500,
        sequenceNr: 31,
      },
      {
        id: 35,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 0,
        y: 1000,
        z: 2000,
        sequenceNr: 34,
      },
      {
        id: 36,
        desc: 'Palette 2',
        height: 400,
        group: 2,
        width: 700,
        length: 500,
        turningAllowed: true,
        turned: null,
        stackingAllowed: false,
        stackedOnGood: null,
        x: 700,
        y: 1000,
        z: 2000,
        sequenceNr: 35,
      },
    ],
  },
  algorithm: 'Super-Flo',
  groups: [
    {
      id: 1,
      color: '#b71a1a',
      desc: 'Test AG',
    },
    {
      id: 2,
      color: '#6094e6',
      desc: 'Beispiel SE',
    },
  ],
  calculated: '2022-01-20T18:14:58',
  description: 'exemplary solution',
};
